=== ALW-N/XML-Webstack/validation.dtd
<!ELEMENT products (product+)>
<!ELEMENT product (id, name, price, quantity, category)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT quantity (#PCDATA)>
<!ELEMENT category (#PCDATA)>
<!ATTLIST id type CDATA #REQUIRED>
<!ATTLIST id unique CDATA #REQUIRED>
<!ATTLIST price min CDATA "5">
<!ATTLIST price max CDATA "500">
<!ATTLIST quantity min CDATA "1">
<!ATTLIST quantity max CDATA "1000">
<!ATTLIST category values (Electronics | Clothing | Books) #REQUIRED>

=== ALW-N/XML-Webstack/e-commerce.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- <!DOCTYPE products SYSTEM "validation.dtd"> -->
<products xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="validation.xsd">
  <product>
    <id>123</id>
    <name>Laptop</name>
    <price>400</price>
    <quantity>100</quantity>
    <category>Electronics</category>
  </product>
  <product>
    <id>456</id>
    <name>T-shirt</name>
    <price>20</price>
    <quantity>50</quantity>
    <category>Clothing</category>
  </product>
  <product>
    <id>789</id>
    <name>Silient Patient</name>
    <price>100</price>
    <quantity>100</quantity>
    <category>Books</category>
  </product>
</products>
